<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RtTranslation\Module'                             => __DIR__ . '/Module.php',
  'RtTranslation\Controller\TranslationController'   => __DIR__ . '/src/RtTranslation/Controller/TranslationController.php',
  'RtTranslation\Entity\Key'                         => __DIR__ . '/src/RtTranslation/Entity/Key.php',
  'RtTranslation\Entity\Locale'                      => __DIR__ . '/src/RtTranslation/Entity/Locale.php',
  'RtTranslation\Entity\Translation'                 => __DIR__ . '/src/RtTranslation/Entity/Translation.php',
  'RtTranslation\Form\KeyFilter'                     => __DIR__ . '/src/RtTranslation/Form/KeyFilter.php',
  'RtTranslation\Form\KeyForm'                       => __DIR__ . '/src/RtTranslation/Form/KeyForm.php',
  'RtTranslation\Form\LocaleFilter'                  => __DIR__ . '/src/RtTranslation/Form/LocaleFilter.php',
  'RtTranslation\Form\LocaleForm'                    => __DIR__ . '/src/RtTranslation/Form/LocaleForm.php',
  'RtTranslation\Form\TranslationFilter'             => __DIR__ . '/src/RtTranslation/Form/TranslationFilter.php',
  'RtTranslation\Form\TranslationForm'               => __DIR__ . '/src/RtTranslation/Form/TranslationForm.php',
  'RtTranslation\I18n\Translator\Loader\Database'    => __DIR__ . '/src/RtTranslation/I18n/Translator/Loader/Database.php',
  'RtTranslation\Model\KeyTable'                     => __DIR__ . '/src/RtTranslation/Model/KeyTable.php',
  'RtTranslation\Model\LocaleTable'                  => __DIR__ . '/src/RtTranslation/Model/LocaleTable.php',
  'RtTranslation\Model\TranslationTable'             => __DIR__ . '/src/RtTranslation/Model/TranslationTable.php',
  'RtTranslation\Options\ModuleOptions'              => __DIR__ . '/src/RtTranslation/Options/ModuleOptions.php',
  'RtTranslation\Service\DatabaseLoaderFactory'      => __DIR__ . '/src/RtTranslation/Service/DatabaseLoaderFactory.php',
  'RtTranslation\Service\DatabaseTranslationService' => __DIR__ . '/src/RtTranslation/Service/DatabaseTranslationService.php',
  'RtTranslation\Service\TranslationService'         => __DIR__ . '/src/RtTranslation/Service/TranslationService.php',
);
