<div class=''>
    
    <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    
<?php

    $form = $this->form;
    $form->prepare();
    
    $form   ->setAttribute('method', 'post')
            ->setAttribute("role", "form")
            ->setAttribute("action", $this->url("developer/translation/key/add", array()))
            ->setAttribute("name", "formKey")
            ->setAttribute("id", "formKey")
            ->setAttribute("class", "form-horizontal");
    
    // Render the opening tag
    echo $this->form()->openTag($form);
    ?>
    <div class="form-group ">
        <?php
        $message = $this->form->get("message");
        $message->setAttribute("placeholder", "Message")
                ->setAttribute("class", "form-control")
                ->setAttribute("required", false)
                ->setAttribute("id", "message");
        ?>
        <label for="message" class="col-lg-2 col-md-2 col-sm-2 col-xs-12 control-label"><?php echo $message->getLabel(); ?> <span class="required">*</span></label>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->formInput($message); ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="help-block"><?php echo $this->translate("Message", "RtTranslation"); ?></p>
        </div>
    </div>
        
    <div class="form-group ">
        <?php
        $textDomain = $this->form->get("textDomain");
        $textDomain->setAttribute("placeholder", "textDomain")
                ->setAttribute("class", "form-control")
                ->setAttribute("required", false)
                ->setAttribute("id", "textDomain");
        ?>
        <label for="textDomain" class="col-lg-2 col-md-2 col-sm-2 col-xs-12 control-label"><?php echo $textDomain->getLabel(); ?> <span class="required">*</span></label>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->formInput($textDomain); ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="help-block"><?php echo $this->translate("Text domain", "RtTranslation"); ?></p>
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><button class="btn btn-primary" type="submit"><?php echo $this->translate("Save key message", "RtTranslation"); ?></button></div>
    </div>
<?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<div class="clearfix"></div>