<div class=''>
    
    <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    
<?php

    $form = $this->form;
    $form->prepare();
    
    $form   ->setAttribute('method', 'post')
            ->setAttribute("role", "form")
            ->setAttribute("action", $this->url("developer/translation/locale/add", array()))
            ->setAttribute("name", "formLocale")
            ->setAttribute("id", "formLocale")
            ->setAttribute("class", "form-horizontal");
    
    // Render the opening tag
    echo $this->form()->openTag($form);
    ?>
    <div class="form-group ">
        <?php
        $locale = $this->form->get("locale");
        $locale->setAttribute("placeholder", "locale")
                ->setAttribute("class", "form-control")
                ->setAttribute("required", false)
                ->setAttribute("id", "locale");
        ?>
        <label for="locale" class="col-lg-2 col-md-2 col-sm-2 col-xs-12 control-label"><?php echo $locale->getLabel(); ?> <span class="required">*</span></label>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->formInput($locale); ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="help-block"><?php echo $this->translate("Locale", "RtTranslation"); ?></p>
        </div>
    </div>
        
    <div class="form-group ">
        <?php
        $name = $this->form->get("name");
        $name->setAttribute("placeholder", "name")
                ->setAttribute("class", "form-control")
                ->setAttribute("required", false)
                ->setAttribute("id", "name");
        ?>
        <label for="name" class="col-lg-2 col-md-2 col-sm-2 col-xs-12 control-label"><?php echo $name->getLabel(); ?> <span class="required">*</span></label>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->formInput($name); ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="help-block"><?php echo $this->translate("Name", "RtTranslation"); ?></p>
        </div>
    </div>

    <div class="form-group ">
        <?php
        $default = $this->form->get("default");
        $default   ->setAttribute("class", "form-control")
                    ->setAttribute("required", false)
                    ->setAttribute("id", "default");
        ?>
        <label for="default" class="col-lg-2 col-md-2 col-sm-2 col-xs-12 control-label"><?php echo $default->getLabel(); ?> <span class="required">*</span></label>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->formSelect($default); ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="help-block"><?php echo $this->translate("Default", "RtTranslation"); ?></p>
        </div>
    </div>
    
    <div class="form-group ">
        <?php
        $pluralForms = $this->form->get("pluralForms");
        $pluralForms  ->setAttribute("class", "form-control")
                    ->setAttribute("required", false)
                    ->setAttribute("id", "pluralForms");
        ?>
        <label for="pluralForms" class="col-lg-2 col-md-2 col-sm-2 col-xs-12 control-label"><?php echo $pluralForms->getLabel(); ?> <span class="required">*</span></label>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->formSelect($pluralForms); ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="help-block"><?php echo $this->translate("Plural forms of the locale", "RtTranslation"); ?></p>
        </div>
    </div>
        
    <div class="form-group ">
        <?php
        $published = $this->form->get("published");
        $published  ->setAttribute("class", "form-control")
                    ->setAttribute("required", false)
                    ->setAttribute("id", "published");
        ?>
        <label for="published" class="col-lg-2 col-md-2 col-sm-2 col-xs-12 control-label"><?php echo $published->getLabel(); ?> <span class="required">*</span></label>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->formSelect($published); ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="help-block"><?php echo $this->translate("Publish status of the locale", "RtTranslation"); ?></p>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><button class="btn btn-primary" type="submit"><?php echo $this->translate("Save locale", "RtTranslation"); ?></button></div>
    </div>
<?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<div class="clearfix"></div>