<div class="col-lg-6">
    <h2><?php echo $this->translate("Actions", 'RtTranslation'); ?></h2>
    <ul>
        <li><a href='<?php echo $this->url("developer/translation/locale/add", array()); ?>'><?php echo $this->translate("Add locale", 'RtTranslation'); ?></a></li>
        <li><a href='<?php echo $this->url("developer/translation/locale", array()); ?>'><?php echo $this->translate("List of locales", 'RtTranslation'); ?></a></li>
        <li><a href='<?php echo $this->url("developer/translation/key/add", array()); ?>'><?php echo $this->translate("Add Message key", 'RtTranslation'); ?></a></li>
        <li><a href='<?php echo $this->url("developer/translation/key", array()); ?>'><?php echo $this->translate("List of message keys", 'RtTranslation'); ?></a></li>
        <li><a href='<?php echo $this->url("developer/translation/translation", array()); ?>'><?php echo $this->translate("List of translations", 'RtTranslation'); ?></a></li>
    </ul>    
</div>

<div class="col-lg-6">
    <h2><?php echo $this->translate("Locales", 'RtTranslation'); ?></h2>

    <p><?php echo $this->translate("Current locale", "RtTranslation") . " : " . $this->currentLocale(); ?></p>    
</div>
