<table class="table table-bordered table-hover table-striped">
    <tr>
        <th><?php echo $this->translate("Message", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Text domain", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Action", "RtTranslation"); ?></th>
    </tr>
    <?php
    foreach ($this->paginator as $key){
        echo sprintf("<tr><td>%s</td><td>%s</td><td><a class='btn btn-default' href='".$this->url("developer/translation/key/edit", array("keyId"=>$key->getKeyId()))."'>". $this->translate("Edit", "RtTranslation")."</a></td></tr>", $key->getMessage(), $key->getTextDomain());
    }
    ?>
</table>
<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'RtTranslation'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'developer/translation/key'
    )
);
?>