<table class="table table-bordered table-hover table-striped">
    <tr>
        <th><?php echo $this->translate("Locale", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Message", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Text domain", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Translation", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Plural index", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Published", "RtTranslation"); ?></th>
        <th><?php echo $this->translate("Actions", "RtTranslation"); ?></th>
    </tr>
    <?php
    
    foreach ($this->paginator as $translation){
        echo sprintf("<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>", $translation->getLocale()->getName(), $translation->getKey()->getMessage(), $translation->getKey()->getTextDomain(), $translation->getTranslation(), $translation->getPluralIndex(), $translation->getPublished());
    }
    ?>
</table>
<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'RtTranslation'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'developer/translation/translation'
    )
);
?>