<?php /* @var $collector \DoctrineORMModule\Collector\MappingCollector */ ?>
<div class="zdt-toolbar-entry">
    
    <div class="zdt-toolbar-detail">
        <div class="zdt-toolbar-detail-inner">
            <span class="zdt-toolbar-info zdt-toolbar-info-heading">Locale: <?php echo $this->collector->getLocale(); ?></span>
            <ul><?php 
            $nMissing = 0;
            foreach ($this->collector->getTranslations() as $translate){
                if(!$translate['missing']){
                    $nMissing++;
                    $miss = "";
                }else{
                    $miss = "<span class='label label-danger'></span>";
                }
                echo sprintf("<li>".$miss."[%s] %s</lî>", $translate['textDomain'], $translate['message']);
            } ?>
            </ul>
        </div>
    </div>
    <div class="zdt-toolbar-preview">
        <img height="20" width="20" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAalJREFUeNrM1D9IW1EUx/HEpELtoK3iH7KJWcQmuiouVh1c0oJEraAigpntXhBFXFzUpVtpBRGRqJsWRXBNJkFRtIM6BaXVQayK6ffCz3K5PKtIBgMfHrnnvvPOPfe+589ms75c/vJ8Of4F0+m0O1aGcfzESC4qfIU+xJ9UIV6jwBqr0PUaIWd+RuP/TTiBXo9YLQ6dsSj2MIgAdrDiJsyoX3YbKnGphAErdo5WTOr/EapwdTfBn0ql/E4V1djCKcI4s2LmjC0ipvFCNGPNribraDAPQgneO7FytGAXQ8rR+dAuJ/AHxxjFGysW0wYm8Q2/0K5KPROaZtdhCf3a5e94ofhHXc3YDeZQhCavhKb0KVU3jB+YQRvGtNxGrGNb90zjVuf23y6H1Y+ExrqtG0zFES3tg3pbrOX6dAJMpe9Qak5MUH0xyX5jAAtW1RfaBFPFqnUWo06r8vXAL0Edg4iWeeCxSeacvlVvN/HZiYfUmq67hPvoeeAV7dD1KzY84p/U3/BjPl8v1XTz5izfM2dWGxx/TMIaTZ7HyT1zknoN6/3P/ov9V4ABAGHIYJbYIRDqAAAAAElFTkSuQmCC"/>        
        <span class="zdt-toolbar-info">
            <?php echo $nMissing; ?>/<?php echo count($this->collector->getTranslations()); ?>
        </span>
    </div>
    
    
    
</div>